name: Fotocasa Scraper CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1" # Ejecutar todos los lunes a las 9:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Verify Chromium binary
        run: |
          if [ -f /snap/bin/chromium ]; then
            echo "Chromium binary found at /snap/bin/chromium"
          else
            echo "Chromium binary not found at /snap/bin/chromium"
            exit 1
          fi

      - name: Verify Chromium works
        run: |
          chromium --headless --disable-gpu --dump-dom https://www.example.com

      - name: Verify Chromium installation
        run: |
          which chromium || echo "chromium not found"
          chromium --version || echo "chromium version error"

      - name: Verify Chromedriver installation
        run: |
          which chromedriver || echo "chromedriver not found"
          chromedriver --version || echo "chromedriver version error"

      - name: Run Python script
        run: python main.py
