name: Fotocasa Scraper CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1" # Ejecutar todos los lunes a las 9:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Google Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Verify Chromium installation
        run: |
          which chromium
          chromium --version

      - name: Verify Chromedriver installation
        run: |
          which chromedriver
          chromedriver --version

      - name: Run Python script
        run: python main.py
